name: tzwad_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  ### Base ###
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  dio: ^5.8.0+1
  intl: ^0.19.0
  go_router: ^15.1.1

  ### Image ###
  flutter_svg: ^2.1.0

  ### Local Data ###
  shared_preferences: ^2.5.3

  ### Config App###
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

  ### UI ###
  gap: ^3.0.1

  ### Animation ###
  loading_animation_widget: ^1.3.0

  ### Dummy Data ###
  faker: ^2.2.0
  either_dart: ^1.0.0
  pinput: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/img_splash.png
  branding: assets/images/img_splash.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/img_splash.png
  branding_dark: assets/images/img_splash.png

  android_12:
    image: assets/images/img_splash.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/img_splash.png
    icon_background_color_dark: "#FFFFFF"

  web: false

flutter_icons:
  #  image_path_android: "assets/images/img_logo_with_background.png"
  image_path_ios: "assets/images/img_logo_with_background.png"
  android: false
  ios: true
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translation/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Light.ttf
          weight: 300