var appStrings = {
  "welcome": "",
  'Low': "",
  'Normal': "",
  'High': "",
  'Urgent': "",
  'Something went wrong': "",
  'Item added to cart': "",
  'Item subtracted from cart': "",
  'Insufficient data?': "",
  'Please provide all the profile Information.': "",
  'Not now': "",
  'Add now': "",
  'Connection failed': "",
  'Order submitted!': "",
  "Your order has been successful! You'll receive ordered items in 3-5 days. Your order ID  is":
      "",
  'Ok': "",
  'Enter a valid coupon': "",
  'Coupon applied!': "",
  'Item added to favorite.': "",
  'Item removed from favorite.': "",
  'All Information must be provided': "",
  'fetching success.': "",
  'Request failed': "",
  'No more product found!': "",
  'Loading failed!': "",
  'Please select a state.': "",
  'Loading failed': "",
  'Status change failed': "",
  'Please provide all the information': "",
  'Login failed!': "",
  'Please read and accept the terms and condition': "",
  'Register failed.': "",
  'Welcome back': "",
  'Register to join us': "",
  'Forgot password?': "",
  'Log in': "",
  'Register': "",
  "Don't have an account?": "",
  'Already have an account?': "",
  'Failed to load!': "",
  'Login with Google': "",
  'Register with Google': "",
  'Login with Facebook': "",
  'Register with Facebook': "",
  'Something Went Wrong': "",
  'Reset Password': "",
  "Enter the email you used to create account and we'll send instruction for resetting password":
      "",
  'Enter email': "",
  'Email': "",
  'Send OTP': "",
  'Enter the 4 digit code we sent to to your email in order to reset password':
      "",
  "Didn't received?": "",
  'Send again': "",
  'Wrong OTP Code': "",
  'Username': "",
  'Enter your email/username': "",
  'Password': "",
  'Password must be at least 6 digit.': "",
  'Remember me': "",
  'New password': "",
  'Enter new password': "",
  'Enter at least 6 characters': "",
  'Re enter new password': "",
  'Name': "",
  'Enter name': "",
  'Enter your name': "",
  'Enter a valid name': "",
  'User name': "",
  'Enter user name': "",
  'Enter your username': "",
  'Enter username without space': "",
  'Enter email address': "",
  'Enter your email': "",
  'Enter a valid email': "",
  'Phone Number': "",
  'Enter Phone number': "",
  'Enter your number': "",
  'Country': "",
  'State': "",
  'Enter password': "",
  'Enter password without any space': "",
  'Confirm Password': "",
  'Re enter password': "",
  'Enter the same password': "",
  'Accept all': "",
  'Terms and Conditions': "",
  'Privacy Policy': "",
  'Delete': "",
  'Item removed from cart.': "",
  'Are you sure?': "",
  'This Item will be Deleted.': "",
  'No': "",
  'Yes': "",
  'Add item to cart!': "",
  'Checkout': "",
  'Login to checkout?': "",
  'You have to  login to proceed the checkout.': "",
  'Cancel': "",
  'Add new address': "",
  'Product': "",
  'Subtotal': "",
  'Shipping cost': "",
  'Select a shipping address.': "",
  'Coupon discount': "",
  'Total': "",
  'Coupon code': "",
  'Enter Coupon code': "",
  'Apply Coupon code': "",
  'Connection failed.': "",
  'Chose a payment method': "",
  'An error occurred': "",
  'Pay & Confirm': "",
  'No shipping address selected?': "",
  'Please add or select Shipping address to proceed your payment.': "",
  'Payment failed!': "",
  'You have agree to our Terms & Conditions.': "",
  'Select a payment Gateway': "",
  'Select an image from gallery': "",
  'Continue': "",
  'Take an image to proceed': "",
  "Your order has been successful! You'll receive ordered items in 3-5 days.":
      "",
  "Your order ID  is": "",
  'Current address': "",
  "Add shipping address or all the account information's": "",
  'Oops!': "",
  'Payment successful!': "",
  "We're getting problems with your payment methods and we couldn't proceed your order.":
      "",
  "Your order has been successful! You'll receive ordered items in 3-5 days. Your order ID is":
      "",
  'Back to home': "",
  'Track your order': "",
  'Add to cart': "",
  'In Stock': "",
  'Description': "",
  'No description available.': "",
  'Additional Information': "",
  'Related products': "",
  'Select all attribute to proceed.': "",
  'Review': "",
  'No Review submitted yet': "",
  'Your rating': "",
  'Your review': "",
  'Write yor feedback.': "",
  'Submit': "",
  'Please write a feedback': "",
  'Connection Failed.': "",
  'Select attributes:': "",
  'Add to cart.': "",
  'Select all attribute to proceed': "",
  'Add items to favorite': "",
  'No product found': "",
  'All Products': "",
  'Something went wrong!': "",
  'Deal of the Day': "",
  'Categories': "",
  'Popularity': "",
  'Latest': "",
  'Lower price': "",
  'Higher price': "",
  'My cart': "",
  'My favorite': "",
  'Press again to exit': "",
  'Search your need here': "",
  'Featured products': "",
  'Campaigns': "",
  'Product added to cart.': "",
  'View details': "",
  "See all": "",
  'Please turn on your internet connection': "",
  "Connection failed!": "",
  'Failed to load data.': "",
  'Image': "",
  'Quantity': "",
  'Price': "",
  'Shipping': "",
  'Tax': "",
  'Discount': "",
  'Payment status': "",
  'My orders': "",
  'No order found.': "",
  'No more order found': "",
  'Invalid developer keys': "",
  "Flutterwave payment": "",
  "Pay": "",
  'Are you sure?'
      'Are you sure?': "",
  'Your payment process will get terminated.': "",
  'Return': "",
  'Payment has been cancelled.': "",
  'Payment cancelled!': "",
  'Payment has been expired.': "",
  'Payment failed': "",
  'All categories': "",
  'Sub-category': "",
  'No sub-category available': "",
  'Filter Price': "",
  'Average Rating': "",
  'Reset Filter': "",
  'Apply Filter': "",
  'No data has been found!': "",
  'Change Password': "",
  'Current password': "",
  'Enter current password': "",
  'Enter at least 6 characters'
      'Enter at least 6 characters': "",
  'Save Changes': "",
  "Please give all the information properly": "",
  'Manage Account': "",
  'Zip code': "",
  'Enter a valid address': "",
  'Enter your address': "",
  'Enter your city': "",
  'City': "",
  'Enter zip code': "",
  'Address': "",
  'Enter your zip code': "",
  'Enter a valid zip code': "",
  'Enter a valid city name': "",
  'Enter address name': "",
  'Add New Address': "",
  'Enter more then 3 character': "",
  'Enter your address.': "",
  'Add Address': "",
  "You 'll have to login/register to edit or see your profile info.": "",
  'Login/Register': "",
  'Shipping Address': "",
  'My Orders': "",
  'Support Ticket': "",
  'Log Out': "",
  'Shipping addresses': "",
  'No address added yet!': "",
  'This address will be deleted permanently.': "",
  "Couldn't add Ticket": "",
  'Add new ticket': "",
  'Title': "",
  'Enter a title': "",
  'Enter a valid title': "",
  'Enter a subject': "",
  'Enter a valid subject': "",
  'Enter a subject with more then 5 character': "",
  'Priority': "",
  'Describe your issue': "",
  'You have to give some description': "",
  'Add Ticket': "",
  'All tickets': "",
  'No ticket found.': "",
  'No more ticket found': "",
  'Write message': "",
  'File': "",
  'Choose file': "",
  'No file chosen': "",
  'Notify via mail': "",
  'Send': "",
  'No Message has been found!': "",
  'Status': "",
  'Could not load any messages': "",
  'open': "",
  'close': "",
  'low': "",
  'medium': "",
  'high': "",
  'urgent': "",
  'Hello': "",
  'Welcome to Grenmart!': "",
  'See All': "",
  'Select Country': "",
  'Search Country': "",
  'Select State': "",
  'Search State': "",
  'No result found': "",
  "Password Change Unavailable. We're sorry, but users who have signed up or logged in using their Google or Facebook accounts do not have the option to change their password directly on this platform. ":
      "",
  'Password changed successfully': "",
  'See All': "",
  'See All': "",
  'See All': "",
};
